### ISSUE TITLE
Error getting while ng serve ? 

### ISSUE THREAD

**Issue by PrasanthMV1987** [willsoto/ng-chartist#235] opened 2019-02-09 10:44 UTC
I am getting the follwing error while doing ng serve . `ERROR in multi ./node_modules/chartist/dist/chartist.css ./node_modules/ng2-slim-loading-bar/style.css ./node_modules/c3/c3.min.css ./node_modules/ngx-toastr/toastr.css ./node_modules/quill/dist/quill.snow.css ./node_modules/quill/dist/quill.bubble.css ./node_modules/angular-calendar/css/angular-calendar.css ./node_modules/dragula/dist/dragula.css ./node_modules/@swimlane/ngx-datatable/release/index.css ./node_modules/@swimlane/ngx-datatable/release/themes/material.css ./node_modules/@swimlane/ngx-datatable/release/assets/icons.css ./src/assets/vendor/css-chart.css ./src/assets/scss/style.scss ./src/styles.css
Module not found: Error: Can't resolve '/node_modules/chartist/dist/chartist.css' in ''
ERROR in multi ./node_modules/chartist/dist/chartist.css ./node_modules/ng2-slim-loading-bar/style.css ./node_modules/c3/c3.min.css ./node_modules/ngx-toastr/toastr.css ./node_modules/quill/dist/quill.snow.css ./node_modules/quill/dist/quill.bubble.css ./node_modules/angular-calendar/css/angular-calendar.css ./node_modules/dragula/dist/dragula.css ./node_modules/@swimlane/ngx-datatable/release/index.css ./node_modules/@swimlane/ngx-datatable/release/themes/material.css ./node_modules/@swimlane/ngx-datatable/release/assets/icons.css ./src/assets/vendor/css-chart.css ./src/assets/scss/style.scss ./src/styles.css
Module not found: Error: Can't resolve '/node_modules/quill/dist/quill.bubble.css' in ''
ERROR in multi ./node_modules/chartist/dist/chartist.css ./node_modules/ng2-slim-loading-bar/style.css ./node_modules/c3/c3.min.css ./node_modules/ngx-toastr/toastr.css ./node_modules/quill/dist/quill.snow.css ./node_modules/quill/dist/quill.bubble.css ./node_modules/angular-calendar/css/angular-calendar.css ./node_modules/dragula/dist/dragula.css ./node_modules/@swimlane/ngx-datatable/release/index.css ./node_modules/@swimlane/ngx-datatable/release/themes/material.css ./node_modules/@swimlane/ngx-datatable/release/assets/icons.css ./src/assets/vendor/css-chart.css ./src/assets/scss/style.scss ./src/styles.css
Module not found: Error: Can't resolve '/node_modules/quill/dist/quill.snow.css' in ''
ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.
`

**Comment by hakimio** [comment] 2019-02-09 10:47
Did you specify Chartist CSS exactly as shown in the README:
```
"styles": [
  "node_modules/chartist/dist/chartist.css",
  "src/style.scss"
],
```
Without leading slash.

**Comment by PrasanthMV1987** [comment] 2019-02-09 10:51
Yes , that's is there as below
 "styles": [
                            "node_modules/chartist/dist/chartist.css",
                            "node_modules/ng2-slim-loading-bar/style.css",
                            "node_modules/c3/c3.min.css",
                            "node_modules/ngx-toastr/toastr.css",
                            "node_modules/quill/dist/quill.snow.css",
                            "node_modules/quill/dist/quill.bubble.css",
                            "node_modules/angular-calendar/css/angular-calendar.css",
                            "node_modules/dragula/dist/dragula.css",
                            "node_modules/@swimlane/ngx-datatable/release/index.css",
                            "node_modules/@swimlane/ngx-datatable/release/themes/material.css",
                            "node_modules/@swimlane/ngx-datatable/release/assets/icons.css",
                            "src/assets/vendor/css-chart.css",
                            "src/assets/scss/style.scss",
                            "src/styles.css"
                        ],

**Comment by hakimio** [comment] 2019-02-09 10:52
Did you install all the dependencies? Can you create an example project on github reproducing the issue?

**Comment by hakimio** [comment] 2019-02-09 11:24
You can also try to remove css definitions in angular.json one-by-one to see when the error disappears.

**Comment by willsoto** [comment] 2019-02-09 12:23
It’s really hard to see it cause the formatting is wrong, but it looks like you have multiple errors:

```
 Module not found: Error: Can't resolve '/node_modules/quill/dist/quill.snow.css' in '' ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected. node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected. node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.
```

**Comment by willsoto** [comment] 2019-02-10 14:39
@PrasanthMV1987 I am closing this since I do not believe this is related to us according to the stack trace. Feel free to reopen if it is a problem on our end. Thanks!

**Closed by willsoto** 2019-02-10 14:39 UTC

**Comment by PrasanthMV1987** [comment] 2019-02-10 16:32
Thanks. Got fixed. It was my problem.

**Comment by saisandirikrishna** [comment] 2024-06-22 05:54
Hi @PrasanthMV1987 , I am also getting problem with chartist while upgrading from Angular 11 to 18.

**Error: Can't resolve 'node_modules/chartist/dist/chartist.css' **


I have already used chartist by Including the the  chartist CSS in angular.json in older version which was worked.

"styles": [
              {
                "input": "node_modules/@progress/kendo-theme-default/dist/all.css"
              },
              "src/styles.scss",
              "node_modules/chartist/dist/chartist.css",
              "node_modules/quill/dist/quill.core.css",
              "node_modules/quill/dist/quill.snow.css",
              "node_modules/quill/dist/quill.bubble.css",
              "node_modules/angular-calendar/css/angular-calendar.css",
              "node_modules/dragula/dist/dragula.css",
              "node_modules/perfect-scrollbar/css/perfect-scrollbar.css",
              "node_modules/@swimlane/ngx-datatable/index.css",
              "node_modules/@swimlane/ngx-datatable/themes/material.css",
              "node_modules/@swimlane/ngx-datatable/assets/icons.css",
              "src/assets/styles/style.scss",
              "node_modules/primeicons/primeicons.css",
              "node_modules/primeng-lts/resources/themes/saga-orange/theme.css",
              "node_modules/primeng-lts/resources/primeng.min.css"
        
            ],

can you please let me know what changes you did to get fix the issue
